# Sean Sisson
# .bashrc


# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=/usr/pgsql-9.3/bin:$PATH
alias vi=vim
export EDITOR=vim
