# .bashrc

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Common Aliases
alias vi=vim
alias lsl="ls -la"
alias l="ls -l"
alias sl="ls"

# Terminal customizations
export EDITOR=vim
export TERM=xterm-256color

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

# added by travis gem
[ -f /root/.travis/travis.sh ] && source /root/.travis/travis.sh
