# .bashrc

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Common Aliases
alias vi=vim
alias lsl="ls -la"
alias l="ls -l"
alias sl="ls"

export EDITOR=vim
export TERM=xterm-256color
source ~/.git-prompt.sh
PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

# added by travis gem
[ -f /root/.travis/travis.sh ] && source /root/.travis/travis.sh
